import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ResponseProvider } from "@/context/responseContext";
import { RepositoryProvider } from "@/context/repositoryContext";
import "./globals.css";

import Header from "./global/header";
import Footer from "./global/footer";
import Return from "./global/return";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gemini Docs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body className={`flex flex-col ${inter.className} min-h-screen bg-neutral-100`}>
        <ResponseProvider>
          <RepositoryProvider>
            <Header />
            <Return />
            {children}
            <Footer />
          </RepositoryProvider>
        </ResponseProvider>
      </body>
    </html>
  );
}
