import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ResponseProvider } from "@/context/responseContext";
import "./globals.css";

import Header from "./components/header";
import Footer from "./components/footer";
import Return from "./components/return";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gemini Docs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body className={`flex flex-col ${inter.className} min-h-screen bg-neutral-100`}>
        <ResponseProvider>
          <Header />
          <Return />
          {children}
          <Footer />
        </ResponseProvider>
      </body>
    </html>
  );
}
